/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "ما الجديد",
        noLinkConfigured: "لا يوجد رابط",
        varCalciteColorStatusDangerD83020: "var(-calcite-color-status-danger, #d83020)",
        unknownError: "خطأ مجهول",
        unserializableError: "خطأ غير معقول",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
