/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Какво ново?",
        noLinkConfigured: "Няма конфигурирана връзка.",
        varCalciteColorStatusDangerD83020: "var(-calcite-color-status-danger, #d83020)",
        unknownError: "неизвестна грешка",
        unserializableError: "несериозна грешка",
        valueNewUpdatesAvailable: "{value}, нови актуализации"
      })
    }
  }
})
