/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Co je nového?",
        noLinkConfigured: "Žádný odkaz nastaven.",
        varCalciteColorStatusDangerD83020: "var (--calcite-color- status-danger, # d83020)",
        unknownError: "neznámá chyba",
        unserializableError: "neserializovatelná chyba",
        valueNewUpdatesAvailable: "{value}, nové aktualizace k dispozici"
      })
    }
  }
})
