/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Τι νέα;",
        noLinkConfigured: "Δεν έχει ρυθμιστεί σύνδεση.",
        varCalciteColorStatusDangerD83020: "var(-- calcite-color-status-danger, #d83020)",
        unknownError: "άγνωστο σφάλμα",
        unserializableError: "σφάλμα μη ανιχνεύσιμο",
        valueNewUpdatesAvailable: "{value}, νέες διαθέσιμες ενημερώσεις"
      })
    }
  }
})
