/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Lo nuevo",
        noLinkConfigured: "No hay enlace configurado.",
        varCalciteColorStatusDangerD83020: "var(--calcite-color-status-danger, #d83020)",
        unknownError: "error desconocido",
        unserializableError: "error unserializable",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
