/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Mis on uus?",
        noLinkConfigured: "Ühtegi linki pole seadistatud.",
        varCalciteColorStatusDangerD83020: "var(- kaltsiit- värv- seisund- oht, #d83020)",
        unknownError: "tundmatu viga",
        unserializableError: "seeriaviisiline viga",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
