/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Mitä uutta?",
        noLinkConfigured: "Linkkiä ei ole määritetty.",
        varCalciteColorStatusDangerD83020: "var(--kalsite-color-status-danger, #d83020)",
        unknownError: "tuntematon virhe",
        unserializableError: "epätavallinen virhe",
        valueNewUpdatesAvailable: "{value}, uudet päivitykset saatavilla"
      })
    }
  }
})
