/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Quoi de neuf ?",
        noLinkConfigured: "Aucun lien configuré.",
        varCalciteColorStatusDangerD83020: "var(--calcite-color-status-danger, #d83020)",
        unknownError: "erreur inconnue",
        unserializableError: "Erreur non sérialisable",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
