/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "מה חדש",
        noLinkConfigured: "שום קישור לא מוגדר.",
        varCalciteColorStatusDangerD83020: "var(-calcite-color-Danger, #D83020)",
        unknownError: "טעות לא ידועה",
        unserializableError: "טעות בלתי אפשרית",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
