/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Mi újság?",
        noLinkConfigured: "Nincs konfigurálva.",
        varCalciteColorStatusDangerD83020: "var (--calcite- color- status- danger, # d83020)",
        unknownError: "ismeretlen hiba",
        unserializableError: "nem sorozható hiba",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
