/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Apa New",
        noLinkConfigured: "Tidak ada link yang dikonfigurasi.",
        varCalciteColorStatusDangerD83020: "var (--calcite -colors -status- bahaya, # d83020)",
        unknownError: "galat tak dikenal",
        unserializableError: "kesalahan tidak serialisasi",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
