/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Novità",
        noLinkConfigured: "Nessun link configurato.",
        varCalciteColorStatusDangerD83020: "var(--calcite-color-status-danger, #d83020)",
        unknownError: "errore sconosciuto",
        unserializableError: "errore non serializzabile",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
