/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "新着情報",
        noLinkConfigured: "リンクの設定はありません。",
        varCalciteColorStatusDangerD83020: "var(----calcite-color-status-danger, #d83020) 株式会社ドリテック",
        unknownError: "未知のエラー",
        unserializableError: "unserializable エラー",
        valueNewUpdatesAvailable: "{value}、利用できる新しい更新"
      })
    }
  }
})
