/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "새로운 소식",
        noLinkConfigured: "설정된 링크가 없습니다.",
        varCalciteColorStatusDangerD83020: "var(----calcite-color-status-danger, #d83020)를 표현합니다.",
        unknownError: "알 수없는 오류",
        unserializableError: "unserializable 오류",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
