/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Kas naujo",
        noLinkConfigured: "Nenurodyta jokia nuoroda.",
        varCalciteColorStatusDangerD83020: "var (--calcite- color-status-risk, # d83020)",
        unknownError: "nežinoma klaida",
        unserializableError: "nenustatoma klaida",
        valueNewUpdatesAvailable: "{value}, prieinami nauji atnaujinimai"
      })
    }
  }
})
