/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Kas jauns",
        noLinkConfigured: "Nav konfigurēta saite.",
        varCalciteColorStatusDangerD83020: "var(--kalcite-color-status-danger, #d83020)",
        unknownError: "nezināma kļūda",
        unserializableError: "nepārspējama kļūda",
        valueNewUpdatesAvailable: "{value}, pieejami jauni atjauninājumi"
      })
    }
  }
})
