/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Wat is nieuw?",
        noLinkConfigured: "Geen koppeling geconfigureerd.",
        varCalciteColorStatusDangerD83020: "var(--calcite-color-status-danger, #d83020)",
        unknownError: "onbekende fout",
        unserializableError: "onuitwisbare fout",
        valueNewUpdatesAvailable: "{value}, nieuwe updates beschikbaar"
      })
    }
  }
})
