/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Hva er nytt",
        noLinkConfigured: "Ingen lenke konfigurert.",
        varCalciteColorStatusDangerD83020: "var(-calcite-color-status-danger, #d83020)",
        unknownError: "ukjent feil",
        unserializableError: "uiserbar feil",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
