/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Co nowego",
        noLinkConfigured: "Brak skonfigurowanego połączenia.",
        varCalciteColorStatusDangerD83020: "var (-- calcite- color- status- danger, # d83020)",
        unknownError: "nieznany błąd",
        unserializableError: "błąd niezserializowalny",
        valueNewUpdatesAvailable: "{value}, nowe aktualizacje dostępne"
      })
    }
  }
})
