/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "O que há de novo?",
        noLinkConfigured: "Nenhum link configurado.",
        varCalciteColorStatusDangerD83020: "- Calcite-color-status-perigo, #d83020)",
        unknownError: "Erro desconhecido",
        unserializableError: "Erro inserializável",
        valueNewUpdatesAvailable: "{value}, novas atualizações disponíveis"
      })
    }
  }
})
