/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "O que há de novo",
        noLinkConfigured: "Nenhuma ligação configurada.",
        varCalciteColorStatusDangerD83020: "var( -- calcite- cor- estatuto- perigo, # d83020)",
        unknownError: "erro desconhecido",
        unserializableError: "erro inserializável",
        valueNewUpdatesAvailable: "{value}, novas atualizações disponíveis"
      })
    }
  }
})
