/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Ce este nou",
        noLinkConfigured: "Nicio legătură configurată.",
        varCalciteColorStatusDangerD83020: "var (-calcite-color-status-danger, #d83020)",
        unknownError: "Eroare necunoscută",
        unserializableError: "eroare inoperabilă",
        valueNewUpdatesAvailable: "{value}, noi actualizări disponibile"
      })
    }
  }
})
