/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Что нового",
        noLinkConfigured: "Ссылка не настроена.",
        varCalciteColorStatusDangerD83020: "var(--calcite-color-status-danger, #d83020)",
        unknownError: "Неизвестная ошибка",
        unserializableError: "несериализируемая ошибка",
        valueNewUpdatesAvailable: "{value}Доступны новые обновления"
      })
    }
  }
})
