/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Čo je nové?",
        noLinkConfigured: "@ info",
        varCalciteColorStatusDangerD83020: "var(--calcit-color-status-danger #d83020)",
        unknownError: "neznáma chyba",
        unserializableError: "neserializovateľná chyba",
        valueNewUpdatesAvailable: "{value}, nové dostupné aktualizácie"
      })
    }
  }
})
