/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Kaj je novega?",
        noLinkConfigured: "Povezava ni nastavljena.",
        varCalciteColorStatusDangerD83020: "var(--kalcit-color-status-danger, #d83020)",
        unknownError: "neznana napaka",
        unserializableError: "Neizvedljiva napaka",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
