/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "What's New",
        noLinkConfigured: "No link configured.",
        varCalciteColorStatusDangerD83020: "var(--calcite-color-status-danger, #d83020)",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
