/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Vad är nytt",
        noLinkConfigured: "Ingen länk konfigurerad.",
        varCalciteColorStatusDangerD83020: "Var(-kalcit-färg-status-fara, #d83020)",
        unknownError: "Okänd fel",
        unserializableError: "oserialiserbart fel",
        valueNewUpdatesAvailable: "{value}nya uppdateringar tillgängliga"
      })
    }
  }
})
