/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "อะไรใหม่",
        noLinkConfigured: "ยังไม่มีการปรับแต่งที่อยู่เชื่อมโยง",
        varCalciteColorStatusDangerD83020: "VARIANCE(-- Ccalite-color-status-danguage, # d83020)",
        unknownError: "ข้อผิดพลาดไม่ทราบสาเหตุ",
        unserializableError: "ข้อผิดพลาดที่ไม่สามารถตรวจสอบได้",
        valueNewUpdatesAvailable: "{value}การปรับปรุงใหม่ที่มีอยู่"
      })
    }
  }
})
