/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "What's New",
        noLinkConfigured: "Hiçbir bağlantı yapılandırılmadı.",
        varCalciteColorStatusDangerD83020: "Var(-calcite-color-status-danger, #d83020)",
        unknownError: "Bilinmeyen hata",
        unserializableError: "Başarısız olmayan hata",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
