/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Що нового",
        noLinkConfigured: "Не налаштовується посилання.",
        varCalciteColorStatusDangerD83020: "var(-calcite-color-status-danger, #d83020)",
        unknownError: "Невідома помилка",
        unserializableError: "несеріалізована помилка",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
