/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Cái gì mới?",
        noLinkConfigured: "Chưa cấu hình liên kết.",
        varCalciteColorStatusDangerD83020: "var (--calcite-color-status-do nguy hiểm, #d83020)",
        unknownError: "lỗi không rõ",
        unserializableError: "Lỗi không thể gửi đi được",
        valueNewUpdatesAvailable: "{value}, new updates available"
      })
    }
  }
})
