/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "新的是什么",
        noLinkConfigured: "未設定連結 。",
        varCalciteColorStatusDangerD83020: "var(- calcite- color- status- danger, #d83020) 。",
        unknownError: "未知的錯誤",
        unserializableError: "不串連的錯誤",
        valueNewUpdatesAvailable: "{value},有新的更新"
      })
    }
  }
})
